# Generated by Django 5.0.3 on 2024-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_sharing', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='media/profile_pictures/default.jpg', upload_to='media/profile_pictures'),
        ),
    ]
