# Generated by Django 5.0.3 on 2024-03-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_sharing', '0004_alter_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30000)),
            ],
        ),
    ]
