# Generated by Django 5.0.3 on 2024-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_sharing', '0009_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='response',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
