# Generated by Django 5.0.4 on 2024-05-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_sharing', '0010_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='content_sharing.post'),
            preserve_default=False,
        ),
    ]
